"""Regenerates firmware/glyphs.py from the PNG source art in
hardware/glyphs/. Run after adding or changing a glyph:

    .venv/bin/pip install pillow
    .venv/bin/python3 tools/gen_glyphs.py

See tasks/ongoing/0023-glyph-table-and-digits.md for the design decision.
"""

import pathlib

from PIL import Image

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
GLYPHS_DIR = REPO_ROOT / "hardware" / "glyphs"
OUTPUT_PATH = REPO_ROOT / "firmware" / "glyphs.py"

GLYPH_SIZE = 128  # the ScreenKey's documented resolution; see hardware/README.md

PLACEHOLDER_ID = 0x00

# emoji_id: source PNG file name, per docs/wire-protocol.md's "Emoji IDs"
SOURCES = {
    0xF1: "1.png",
    0xF2: "2.png",
    0xF3: "3.png",
    0xF4: "4.png",
    0xF5: "5.png",
    0xF6: "6.png",
}

HEADER = '''"""Generated by tools/gen_glyphs.py from the PNG source art in
hardware/glyphs/. Do not edit by hand — edit the source PNGs and re-run
the generator.

Maps a wire-protocol emoji ID (docs/wire-protocol.md, "Emoji IDs") to a
one-bit glyph. See tasks/ongoing/0023-glyph-table-and-digits.md for the
design decision.
"""

import displayio

# emoji_id: (packed 1-bit bitmap, width, height). Bit 1 is foreground,
# bit 0 is background; packed row-major, MSB first.
GLYPHS = {
'''

FOOTER = '''

_bitmap_cache = {}


def _unpack_bitmap(glyph_id):
    cached = _bitmap_cache.get(glyph_id)
    if cached is not None:
        return cached

    packed, width, height = GLYPHS[glyph_id]
    bitmap = displayio.Bitmap(width, height, 2)
    bytes_per_row = (width + 7) // 8
    for y in range(height):
        row_offset = y * bytes_per_row
        for x in range(width):
            byte = packed[row_offset + x // 8]
            bitmap[y * width + x] = (byte >> (7 - (x % 8))) & 1

    _bitmap_cache[glyph_id] = bitmap
    return bitmap


def lookup(emoji_id, foreground, background):
    """Return a TileGrid for `emoji_id`, colored `foreground` on `background`.

    An unknown `emoji_id` draws the placeholder glyph instead of raising,
    so a bad ID from the wire still shows something on the key.
    """
    glyph_id = emoji_id if emoji_id in GLYPHS else PLACEHOLDER_ID
    bitmap = _unpack_bitmap(glyph_id)

    palette = displayio.Palette(2)
    palette[0] = background
    palette[1] = foreground

    return displayio.TileGrid(bitmap, pixel_shader=palette)
'''


def _load_glyph(path):
    """Load a PNG as packed 1-bit-per-pixel bytes, MSB first, row-major.

    Mode "1" packs exactly this way in `Image.tobytes()` — bit 1 for a
    pixel value of 255, no inter-row padding since `GLYPH_SIZE` is a
    multiple of 8 — so no manual bit-packing is needed.
    """
    image = Image.open(path).convert("1")
    if image.size != (GLYPH_SIZE, GLYPH_SIZE):
        raise ValueError(
            "{} is {}x{}, want {}x{}".format(
                path, image.width, image.height, GLYPH_SIZE, GLYPH_SIZE
            )
        )
    return image.tobytes()


def _placeholder_bitmap():
    """A filled box: every pixel set, so an unknown ID draws something visible."""
    return b"\xff" * ((GLYPH_SIZE // 8) * GLYPH_SIZE)


def _format_entries(glyphs):
    lines = []
    for emoji_id in sorted(glyphs):
        packed, width, height = glyphs[emoji_id]
        lines.append(
            "    0x{:02X}: ({!r}, {}, {}),".format(emoji_id, packed, width, height)
        )
    return "\n".join(lines)


def main():
    glyphs = {PLACEHOLDER_ID: (_placeholder_bitmap(), GLYPH_SIZE, GLYPH_SIZE)}
    for emoji_id, filename in SOURCES.items():
        glyphs[emoji_id] = (_load_glyph(GLYPHS_DIR / filename), GLYPH_SIZE, GLYPH_SIZE)

    placeholder_hex = "0x{:02X}".format(PLACEHOLDER_ID)
    module_source = (
        HEADER
        + _format_entries(glyphs)
        + "\n}\n\nPLACEHOLDER_ID = "
        + placeholder_hex
        + FOOTER
    )
    OUTPUT_PATH.write_text(module_source)
    print("wrote", OUTPUT_PATH)


if __name__ == "__main__":
    main()
